### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by Davethewhite** [c0t088/libregpio#1]
Good day. I'm not certain I'm writing this at the right place but I had no idea how to communicate with the c0t088. I had sensors working on a pi2 but it's dead. Now we have a "lePotato sbc" no sensors appears to work... further reading and it seems le potato is different. Any idea how we should use your program to enable the GPIO pins? I'm not a programmer... I'm a network IT guy... do you know who could help?

**Comment by c0t088** [comment]
Hi. You can go through the documentation in this link: https://libregpio.readthedocs.io/en/latest/

Sadly, LePotato is not a drop-in replacement for rpi. Libre Computer recommends using gpiod to handle GPIO. 

I wrote this code to run gpiod commands via Python, in a way thats is more familiar to me and user friendly (in my opinion). Please, keep in mind that the code hasn´t been broadly tested. I seems to work fine in basic input and output operations, not yet for PWM and the likes. I've tested a relay, PIR motion sensor, Soil moisture sensor and LED's without issues.

Hope this helps.
