### ISSUE TITLE
Include some Example of Usage

### ISSUE THREAD

**Issue by Iainrach** [c0t088/libregpio#2]
Found your library and definitely the best solution I've come across so far for controlling Le Potato GPIO.

Suggested it to :-  https://hub.libre.computer/t/how-to-control-gpio-via-python-3/601/32

I don't use Python too much so took me a bit of time to work it out, an example would have made it much easier.

Program to control Four Leds

import time #for timing delays
from libregpio import OUT, IN

LED1 = OUT("GPIOX_18")
LED2 = OUT("GPIOX_6")
LED3 = OUT("GPIOX_7")
LED4 = OUT("GPIOX_5")

for i in range(0,10):
    print("Switching on Led")
    OUT.output(LED1,1)
    time.sleep(.2)
    OUT.output(LED2,1)
    time.sleep(.2)
    OUT.output(LED3,1)
    time.sleep(.2)
    OUT.output(LED4,1)
    time.sleep(1)
    print("Switching off Led")
    OUT.output(LED1,0)
    time.sleep(.2)
    OUT.output(LED2,0)
    time.sleep(.2)
    OUT.output(LED3,0)
    time.sleep(.2)
    OUT.output(LED4,0)
    time.sleep(1)

**Comment by c0t088** [comment]
Hi,

I'm glad the code was helpful. Sorry for not adding links with examples.

You can see see some other examples in this documentation link: https://libregpio.readthedocs.io/en/latest/ 

I wil be adding the link to the readme file. Thanks.
