### ISSUE TITLE
Error when using wait_for_edge

### ISSUE THREAD

**Issue by brianpratt** [c0t088/libregpio#3]
I have a Le Potato running Raspbian 11 Bullseye. I was able to use this library to control an LED and also get the current state of a pushbutton switch.

I next wanted to use wait_for_edge to toggle the LED on a button press, but wait_for_edge always produces an error for me.

Using the example in the documentation, saved as "button_test.py":
```
import libregpio as GPIO

# set pin GPIOX_12 to be used as an input
pin = GPIO.IN('GPIOX_12')

# wait for a rising-edge event. Bias is set to pull-down
value = pin.wait_for_edge(bias='pull-down', edge='rising')

# print event value
print(value)

GPIO.cleanup()
```

And running it with "python button_test.py":
```
gpiomon: error waiting for events: No such device
Traceback (most recent call last):
  File "/home/admin/python/test_button_edge.py", line 7, in <module>
    value = pin.wait_for_edge(bias='pull-down', edge='rising')
  File "/home/admin/python/libregpio.py", line 91, in wait_for_edge
    edge_val = int(popen(f'gpiomon -r -n 1 {al} -B {bias} -F "%e" {self.GPIOCHIP} {self.pin}').read())
ValueError: invalid literal for int() with base 10: ''
```

Where I think the first error is the most important: **gpiomon: error waiting for events: No such device**

Am I missing something? I would love to get this working rather than having to poll the button state myself!

**Comment by c0t088** [comment]
This project was tested on Armbian Jammy 23.02.2. It was not tested on Raspbian. You can try installing these libraries:

```
sudo apt-get install libgpiod-dev libgpiod-utils
```

**Comment by brianpratt** [comment]
Thanks for the reply and the additional information!

I tried to install the suggested packages on Raspbian, but only libgpiod-dev was available. I got the same "No such device" error from gpiomon.

Maybe I will try Armbian on my board

**Comment by brianpratt** [comment]
Reporting back - I installed Armbian 23.02.2 Bullseye and the wait_for_edge call now works.
